### ISSUE TITLE
Are external runners supported?

### ISSUE THREAD

**Issue by lucc** [MatthiasLohr/munin-plugins-gitlab#39]
I installed this plugin on my gitlab server which also has a runner installed and the graphs for the runner work fine.  Now I installed the plugin (only linking gitlab_ci_builds  and gitlab_ci_builds_current to /etc/munin/plugins) on an external runner instance that is connected to my gitlab instance but I can not get the plugin to work.

So: Are external runners supported by this plugin?

**Comment by MatthiasLohr** [comment]
The plugin accesses the GitLab's server instance database, which does not care if a build is executed by an "external runner" (actually, there are no "internal runners"). Since runners do not have a database like the server, the reply is quite simple: Yes and no.

Yes, because it's contained in the server's build database tables, no because it's not designed to contact a runner directly.
